// ==============
// INIT VARIABLES
// ==============

~winner = 3; // just an initialization value
~letterMeasure = 0; // just an initialization value
~letterMeasureFlag = 0; // init value
~transpRH = 0;
~transpLH = 0;
~referendumArray = [
	/* 0 */ "faster?",
	/* 1 */ "slower?",
	/* 2 */ "transpose pretty?",
	/* 3 */ "transpose prettier?",
	/* 4 */ "make mozart great again?",
	/* 5 */ "chaos?"
];